Online_Courier_Service_Management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Online Courier Service Management Admin'
admin.site.site_title = 'Online Courier Service Management Admin Portal'
admin.site.index_title = 'Welcome to Online Courier Service Management Admin Portal'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('parcels.urls')),
    path('', include('jobs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
                   static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jobs/urls.py
from django.urls import path

import jobs.views as job_views

app_name = 'jobs'

urlpatterns = [
    path('jobs/', job_views.JobListView.as_view(), name='list'),
    path('jobs/<int:pk>/', job_views.JobDetailView.as_view(), name='detail'),
    path('jobs/<int:pk>/apply', job_views.JobApplyView.as_view(), name='apply'),
]

parcels/urls.py
from django.urls import path, reverse

from parcels import views as parcel_views

app_name = 'parcels'

urlpatterns = [
    path('cost-calculator/', parcel_views.CostCalculatorView.as_view(), name='cost_calculator'),
    path('parcels/', parcel_views.ParcelListView.as_view(), name='list'),
    path('parcels/<int:pk>/', parcel_views.ParcelDetailView.as_view(), name='detail'),
    path('parcels/<int:pk>/issue/create', parcel_views.IssueCreateView.as_view(), name='create_issue'),
    path('parcels/create/', parcel_views.ParcelCreateView.as_view(), name='create'),
    path('parcels/track', parcel_views.ParcelTrackView.as_view(), name='track'),
    path('parcels/<int:pk>/update', parcel_views.ParcelUpdateView.as_view(), name='update'),
    path('parcels/<int:pk>/delete', parcel_views.ParcelDeleteView.as_view(), name='delete'),
]

parcels/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import reverse

from users.models import Customer, DeliveryAgent


# Create your models here.

"""List of parcels model."""


class Address(models.Model):
    """
    Address model for creating address instance in database.

    :ivar country:
    :vartype country: django.db.models.CharField

    :ivar city:
    :vartype city: django.db.models.CharField

    :ivar street:
    :vartype street: django.db.models.CharField

    :ivar zip:
    :vartype zip: django.db.models.CharField
    """
    country = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    street = models.CharField(max_length=20)
    zip = models.CharField(max_length=20)

    def save(self, *args, **kwargs):
        """
        This funtcion will be called on address instance save.

        :param args: Arguments data.
        :param kwargs: Kwargs data.
        :return: None
        """
        super(Address, self).save(*args, **kwargs)


class Receiver(models.Model):
    """
    Receiver model for creating receiver instance in database.

    :ivar name: Receiver name.
    :vartype name: django.db.models.CharField

    :ivar email: Receiver email.
    :vartype email: django.db.models.EmailField

    :ivar phone: Receiver phone.
    :vartype phone: django.db.models.CharField

    :ivar address: Receiver address.
    :vartype address: Address
    """
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    address = models.OneToOneField(Address, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        """
        This function will be called on receiver instance save.

        :param args: Arguments data.
        :param kwargs: Kwargs data.
        :return: None
        """
        super(Receiver, self).save(*args, **kwargs)


class Parcel(models.Model):
    """
    Parcel model for creating parcel instance in database.

    :ivar title: Parcel title.
    :vartype title: django.db.models.CharField

    :ivar type: Parcel type.
    :vartype type: django.db.models.CharField

    :ivar status: Parcel status.
    :vartype status: django.db.models.CharField

    :ivar pickup_address: Parcel pickup-address.
    :vartype pickup_address: Address

    :ivar receiver: Parcel receiver.
    :vartype receiver: Receiver

    :ivar booked_on: Parcel booking time.
    :vartype booked_on: django.db.models.DateTimeField

    :ivar booked_by: Parcel creator.
    :vartype booked_by: Customer

    :ivar delivery_agent: Parcel delivery-agent.
    :vartype delivery_agent: DeliveryAgent
    """

    TYPE = [
        ('money', 'Money'),
        ('fruits', 'Fruits'),
        ('fragile', 'Fragile'),
        ('document', 'Document'),
        ('furniture', 'Furniture'),
        ('perishable', 'Perishable'),
        ('electronics', 'Electronics'),
    ]
    STATUS = [
        ('on_delivery', 'On Delivery'),
        ('processing', 'Processing'),
        ('delivered', 'Delivered'),
        ('pending', 'Pending'),
        ('picked', 'Picked'),
    ]
    title = models.CharField(max_length=100)
    type = models.CharField(max_length=20, choices=TYPE, blank=True)
    status = models.CharField(max_length=100, choices=STATUS, default='pending', blank=True)
    pickup_address = models.OneToOneField(Address, on_delete=models.CASCADE)
    receiver = models.OneToOneField(Receiver, on_delete=models.CASCADE)
    booked_on = models.DateTimeField(auto_now_add=True, editable=False)
    booked_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='booked_by', editable=False)
    delivery_agent = models.ForeignKey(DeliveryAgent, blank=True, on_delete=models.CASCADE)

    def get_absolute_url(self):
        """
        Function to get absolute url of parcel objects.

        :return: Absolute url of the instance.
        :rtype: django.shortcuts.reverse
        """

        return reverse('parcels:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.pk)

    def save(self, *args, **kwargs):
        """
        This function will be called on parcel instance save.

        :param args: Arguments data.
        :param kwargs: Kwargs data.
        :return: void
        """
        super(Parcel, self).save(*args, **kwargs)


class Issue(models.Model):
    """
    Issue model for creating issue instance in database.

    :ivar category: Issue category.
    :vartype category: django.db.models.CharField

    :ivar status: Issue status.
    :vartype status: django.db.models.CharField

    :ivar message: Issue description.
    :vartype message: django.db.models.CharField

    :ivar reply: Reply from admin.
    :vartype reply: django.db.models.CharField

    :ivar parcel: Issue created for this parcel id.
    :vartype parcel: Parcel
    """

    CATEGORY = [
        ('delivery', 'Delivery'),
        ('product', 'Product'),
        ('delivery_agent', 'Delivery Agent')
    ]
    STATUS = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('solved', 'Solved'),
    ]
    category = models.CharField(max_length=20, choices=CATEGORY, blank=True)
    status = models.CharField(max_length=20, choices=STATUS, blank=True)
    message = models.CharField(max_length=1000)
    reply = models.CharField(max_length=1000, blank=True)
    parcel = models.ForeignKey(Parcel, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        """
        This function will be called on issue instance save.

        :param args: Arguments data.
        :param kwargs: Kwargs data.
        :return: void
        """
        super(Issue, self).save(*args, **kwargs)

parcels/views.py
from decouple import config
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.views.generic import DetailView, ListView, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import ParcelTrackForm, CostCalculatorForm, AddressForm, ReceiverForm, ParcelForm
from .models import Parcel, Address, Issue


# Create your views here.

"""List of parcels views"""


class CostCalculatorView(FormView):
    form_class = CostCalculatorForm
    template_name = 'parcels/cost_calculator.html'

    def post(self, request, *args, **kwargs):
        if request.POST['weight'] == '0':
            messages.error(request, 'Weight cannot be 0')
            return redirect('parcels:cost_calculator')
        unit_price = 15.0
        minimum_cost = 60.0
        if request.POST['area'] == 'outside':
            unit_price = 30.0
            minimum_cost = 120.0

        charge = max(minimum_cost, unit_price * float(request.POST['weight']))
        messages.success(request, f'Estimated shipping cost is {charge} taka')
        return redirect('parcels:cost_calculator')


class ParcelListView(LoginRequiredMixin, ListView):
    """This class handles parcel list view requests from the customers."""

    def get_queryset(self):
        """
        This function retrieve objects from database by query.

        :return: list of parcel objects placed by the requesting user.
        :rtype: list
        """
        return Parcel.objects.filter(booked_by=self.request.user)


class ParcelDetailView(DetailView):
    """
    This class handles parcel detail view requests from the customers.

    :ivar model: Base model of ParcelDetailView.
    :vartype model: django.db.models.Model
    """
    model = Parcel

    def get(self, request, *args, **kwargs):
        """
        This function will be called on get request of ParcelDetailVIew.

        :param request: Type of request from the customers.
        :param args: Holds other values.
        :param kwargs: Holds other values.
        :return: Return render template view.
        :rtype: django.shortcuts.render
        """
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return render(request, 'parcels/' + self.object.status + '.html', context)


class ParcelCreateView(LoginRequiredMixin, CreateView):
    """
    This class handles parcel create requests from the customers.

    :ivar model: Base model of ParcelCreateView.
    :vartype model: django.db.models.Model

    :ivar fields: Name of the fields needs to provide to create a parcel.
    :vartype fields: list

    :ivar template_name: Name of the template to render ParcelCreateView.
    :vartype template_name: str
    """
    model = Parcel
    fields = ['title', 'type', ]
    template_name = 'parcels/parcel_form.html'

    def get(self, request, *args, **kwargs):
        """
        This function will be called on get request of ParcelCreateView.

        :param request: Request data from the user.
        :param args: Holds other arguments values.
        :param kwargs: Holds kwargs values.

        :ivar parcel_form: Form to fill about parcel information.
        :vartype parcel_form: django.forms.Form

        :ivar pickup_address_form: Form to fill about pickup address information.
        :vartype pickup_address_form: django.forms.Form

        :ivar receiver_form: Form to fill about receiver information.
        :vartype receiver_form: django.forms.Form

        :ivar receiver_address_form: Form to fill about receiver address information.
        :vartype receiver_address_form: django.forms.Form

        :ivar context: Context data to return.
        :vartype context: dict

        :return: Render template view.
        :rtype: django.shortcuts.render
        """
        parcel_form = self.get_form()
        pickup_address_form = AddressForm()
        receiver_form = ReceiverForm()
        receiver_address_form = AddressForm()
        context = {
            'parcel_form': parcel_form,
            'pickup_address_form': pickup_address_form,
            'receiver_form': receiver_form,
            'receiver_address_form': receiver_address_form,
        }
        return render(request=request, template_name=self.get_template_names(), context=context)

    def post(self, request, *args, **kwargs):
        """
        This function will be called on post request of ParcelCreateView.

        :param request: Request data from the user.
        :param args: Holds other arguments values.
        :param kwargs: Holds kwargs values.

        :ivar parcel: Parcel object, created from the data provided by the customer in parcel_form.
        :vartype parcel: Prcel

        :ivar pickup_address: Parcel pickup address, object created from the data provided by the customer in pickup_address_form.
        :vartype pickup_address: Address

        :ivar receiver: Receiver of the parcel, object created from the data provided by the customer in receiver_form.
        :vartype receiver: Receiver

        :ivar receiver_address: Parcel receivers address,  object created from the data provided by the customer in receiver_address_form.
        :vartype receiver_address: Address

        :ivar sender_message: Message to send to sender on parcel creation.
        :vartype sender_message: str

        :ivar receiver_message: Message to send to receiver on parcel creation.
        :vartype receiver_message: str

        :return: Render template view.
        :rtype: django.shortcuts.redirect
        """
        parcel = ParcelForm(request.POST).save()
        pickup_address = Address(country=request.POST.getlist('country')[0], city=request.POST.getlist('city')[0],
                                 street=request.POST.getlist('street')[0], zip=request.POST.getlist('zip')[0])
        pickup_address.save()
        receiver_address = Address(country=request.POST.getlist('country')[1], city=request.POST.getlist('city')[1],
                                   street=request.POST.getlist('street')[1], zip=request.POST.getlist('zip')[1])
        receiver_address.save()

        receiver = ReceiverForm(request.POST).save()
        receiver.address = receiver_address
        receiver.save()
        parcel.pickup_address = pickup_address
        parcel.receiver = receiver
        parcel.booked_by = request.user
        parcel.save()
        messages.success(request, 'Your parcel has been placed successfully')

        sender_message = "You are receiving this email because you have placed a new parcel at "
        receiver_message = "You are receiving this email because a new parcel has been placed for your at "

        message = f"{request.META['HTTP_HOST']}. Please visit our website to know more." + \
                  f"\n\nYour parcel tracking ID: {parcel.id}" + \
                  f"\n\nThanks for using our service!" + \
                  f"\n\nThe {request.META['HTTP_HOST']} team"

        send_mail(
            subject='New Parcel',
            message=sender_message + message,
            from_email=config('EMAIL'),
            recipient_list=[parcel.booked_by.email],
        )

        send_mail(
            subject='New Parcel',
            message=receiver_message + message,
            from_email=config('EMAIL'),
            recipient_list=[parcel.receiver.email],
        )

        return redirect('parcels:list')


class ParcelUpdateView(UserPassesTestMixin, UpdateView):
    """
    This class handles parcel update requests from customers.

    :ivar model: Base model of ParcelUpdateView.
    :vartype model: django.db.models.Model

    :ivar fields: Name of the fields of parcel to allow change from the customers.
    :vartype fields: list

    :ivar template_name: Name of the template to render ParcelUpdateView.
    :vartype template_name: str
    """

    def test_func(self):
        """
        Function for checking access permission of requesting user to this view.

        :return: Return true if user passes test.
        :rtype: bool
        """
        return self.request.user == self.get_object().booked_by

    model = Parcel
    fields = ['type', 'city', 'street', 'zip', 'email', 'phone', ]
    template_name = 'parcels/parcel_update.html'


class ParcelDeleteView(UserPassesTestMixin, DeleteView):
    """
    This class handles parcel delete requests from customers.

    :ivar model: Base model of ParcelDeleteView.
    :vartype model: django.db.models.Model
    """

    def test_func(self):
        """
        Function for checking access permission of requesting user to this view.

        :return: Return true if user passes test.
        :rtype: bool
        """
        return self.request.user == self.get_object().booked_by

    model = Parcel
    # success_url = 'parcels:parcels'  # fixme: having trouble here for success url


class ParcelTrackView(FormView):
    """
    This class handles parcel track requests from customers.

    :ivar form_class: Form to fill to track parcel.
    :vartype form_class: django.forms.Form

    :ivar template_name: Name of the template to render ParcelTrackView.
    :vartype template_name: str
    """
    form_class = ParcelTrackForm
    template_name = 'parcels/parcel_track.html'

    def post(self, request, *args, **kwargs):
        """
        This function will be called on post request of ParcelTrackView.

        :param request: Request data from the user.
        :param args: Holds other arguments values.
        :param kwargs: Holds kwargs values.
        :return: Redirect to parcel urls.
        :rtype: django.shortcuts.redirect
        """
        try:
            parcel = Parcel.objects.get(pk=request.POST['parcel_id'])
            print(parcel)
            return redirect('parcels:detail', pk=parcel.pk)
        except Exception as e:

templates/parcels/cost_calculator.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}

{% block content %}
    <div class="content-section">
      <form method="post">
          {% bootstrap_messages %}
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="d-grid gap-2">
              <button class="btn btn-outline-info" type="submit">Calculate</button>
          </div>
      </form>
    </div>
{% endblock %}

templates/parcels/delivered.html
{% extends 'base.html' %}
{% load static %}

{% block override_style %} <link rel="stylesheet" href=" {% static 'parcels/css/style_delivered.css' %}"> {% endblock %}

{% block content %}
    <!------ Track Parcel content ------->
	<div class="progress">
		<ul class="ul">
			<li>
				<img src="{% static 'images/pending.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>Pending</p>
			</li>
			<li>
				<img src="{% static 'images/processing.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>Processing</p>
			</li>
            <li>
				<img src="{% static 'images/picked.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>Picked</p>
			</li>
			<li>
				<img src="{% static 'images/on-delivery.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>On Delivery</p>
			</li>
			<li>
				<img src="{% static 'images/delivered.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>Delivered</p>
			</li>
		</ul>
	</div>
{% endblock %}

templates/parcels/issue_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}


{% block content %}
    <div class="content-section">
      <form method="post">
          {% bootstrap_messages %}
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="d-grid gap-2">
              <button class="btn btn-outline-info" type="submit">Submit</button>
          </div>
      </form>
    </div>
{% endblock %}

templates/parcels/on_delivery.html
{% extends 'base.html' %}
{% load static %}

{% block override_style %} <link rel="stylesheet" href=" {% static 'parcels/css/style_on_delivery.css' %}"> {% endblock %}

{% block content %}
    <!------ Track Parcel content ------->
	<div class="progress">
		<ul class="ul">
			<li>
				<img src="{% static 'images/pending.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>Pending</p>
			</li>
			<li>
				<img src="{% static 'images/processing.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>Processing</p>
			</li>
            <li>
				<img src="{% static 'images/picked.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>Picked</p>
			</li>
			<li>
				<img src="{% static 'images/on-delivery.png' %}" alt=""><br>
				<i class="fa fa-refresh"></i>
				<p>On Delivery</p>
			</li>
			<li>
				<img src="{% static 'images/delivered.png' %}" alt=""><br>
				<i class="fa fa-times"></i>
				<p>Delivered</p>
			</li>
		</ul>
	</div>
{% endblock %}

templates/parcels/parcel_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}

{% block content %}
    <div class="content-section">
      <form method="post">
          {% bootstrap_messages %}
          {% csrf_token %}
          <div class="d-grid gap-2">
              <button class="btn btn-outline-info" type="submit">Delete</button>
          </div>
      </form>
    </div>
{% endblock %}

templates/parcels/parcel_detail.html
{% extends 'base.html' %}

{% block override_style %}  {% endblock %}

{% block content %}
    {% block progress %} {% endblock %}
    <p align="center"><a href="{% url 'parcels:create_issue' object.pk %}" class="hero-btn red-btn">Create Issue</a></p>
{% endblock %}

templates/parcels/parcel_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}

{% block content %}
    <div class="content-section">
        <form method="post">
            {% bootstrap_messages %}
            {% csrf_token %}
            {% bootstrap_form parcel_form %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Pickup Location</legend>
                {% bootstrap_form pickup_address_form %}
            </fieldset>
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Receiver Information</legend>
                {% bootstrap_form receiver_form %}
                {% bootstrap_form receiver_address_form %}
            </fieldset>
            <div class="d-grid gap-2">
                <button class="btn btn-outline-info" type="submit">Place</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/parcels/parcel_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}
{% block title %} Jobs {% endblock %}

{% block content %}
    <!-- ------------ Recent Parcels ---------------- -->
    {# context is object_list #}
    {% bootstrap_messages %}
    <section id="jobs">
        <div class="container">
            <h4 align="center"> LIST OF YOUR PARCELS, CLICK TO VIEW PROGRESS </h4><br>
            {% for parcel in object_list %}
                <div class="company-details">
                    <div class="reason-col">
                        <a href="{% url 'parcels:detail' parcel.id %}">
                            <h4><b> {{ parcel.title }} </b></h4>
                            <i class="fa fa-glide-g"></i> <span> Tracking ID: {{ parcel.id }} </span><br>
                            <i class="fa fa-clock-o"></i> <span> Booked On: {{ parcel.booked_on }} </span><br>
                            <i class="fa fa-spinner"></i> <span> Status: {{ parcel.get_status_display }} </span><br>
                        </a>
                    </div>
                </div>
            {% empty %}
                <li>You don't have any parcel yet!</li>
            {% endfor %}
        </div>
        <div align="center" class="d-grid gap-2">
            <a href="{% url 'parcels:create' %}">
                <button class="btn btn-outline-info" type="submit">Place a new parcel</button>
            </a>
        </div>
    </section>
{% endblock %}

templates/parcels/parcel_track.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}

{% block content %}
    <div class="content-section">
      <form method="post">
          {% bootstrap_messages %}
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="d-grid gap-2">
              <button class="btn btn-outline-info" type="submit">Track</button>
          </div>
      </form>
    </div>
{% endblock %}

templates/parcels/parcel_update.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}

{% block content %}
    <div class="content-section">
      <form method="post">
          {% bootstrap_messages %}
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="d-grid gap-2">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form>
    </div>
{% endblock %}

templates/parcels/pending.html
{% extends 'parcels/parcel_detail.html' %}
{% load static %}

{% block override_style %} <link rel="stylesheet" href=" {% static 'parcels/css/style_pending.css' %}"> {% endblock %}

{% block progress %}
    <!------ Track Parcel content ------->
	<div class="progress">
		<ul class="ul">
			<li>
				<img src="{% static 'images/pending.png' %}" alt=""><br>
				<i class="fa fa-refresh"></i>
				<p>Pending</p>
			</li>
			<li>
				<img src="{% static 'images/processing.png' %}" alt=""><br>
				<i class="fa fa-times"></i>
				<p>Processing</p>
			</li>
            <li>
				<img src="{% static 'images/picked.png' %}" alt=""><br>
				<i class="fa fa-times"></i>
				<p>Picked</p>
			</li>
			<li>
				<img src="{% static 'images/on-delivery.png' %}" alt=""><br>
				<i class="fa fa-times"></i>
				<p>On Delivery</p>
			</li>
			<li>
				<img src="{% static 'images/delivered.png' %}" alt=""><br>
				<i class="fa fa-times"></i>
				<p>Delivered</p>
			</li>
		</ul>
	</div>
{% endblock %}

templates/parcels/picked.html
{% extends 'base.html' %}
{% load static %}

{% block override_style %} <link rel="stylesheet" href=" {% static 'parcels/css/style_picked.css' %}"> {% endblock %}

{% block content %}
    <!------ Track Parcel content ------->
	<div class="progress">
		<ul class="ul">
			<li>
				<img src="{% static 'images/pending.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>Pending</p>
			</li>
            <li>
				<img src="{% static 'images/processing.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>Processing</p>
			</li>
			<li>
				<img src="{% static 'images/picked.png' %}" alt=""><br>
				<i class="fa fa-refresh"></i>
				<p>Picked</p>
			</li>
			<li>
				<img src="{% static 'images/on-delivery.png' %}" alt=""><br>
				<i class="fa fa-times"></i>
				<p>On Delivery</p>
			</li>
			<li>
				<img src="{% static 'images/delivered.png' %}" alt=""><br>
				<i class="fa fa-times"></i>
				<p>Delivered</p>
			</li>
		</ul>
	</div>
{% endblock %}

templates/parcels/processing.html
{% extends 'base.html' %}
{% load static %}
{% block override_style %} <link rel="stylesheet" href=" {% static 'parcels/css/style_processing.css' %}"> {% endblock %}

{% block content %}
    <!------ Track Parcel content ------->
	<div class="progress">
		<ul class="ul">
			<li>
				<img src=" {% static 'images/pending.png' %}" alt=""><br>
				<i class="fa fa-check"></i>
				<p>Pending</p>
			</li>
            <li>
				<img src="{% static 'images/processing.png' %}" alt=""><br>
				<i class="fa fa-refresh"></i>
				<p>Processing</p>
			</li>
			<li>
				<img src="{% static 'images/picked.png' %}" alt=""><br>
				<i class="fa fa-times"></i>
				<p>Picked</p>
			</li>
			<li>
				<img src="{% static 'images/on-delivery.png' %}" alt=""><br>
				<i class="fa fa-times"></i>
				<p>On Delivery</p>
			</li>
			<li>
				<img src="{% static 'images/delivered.png' %}" alt=""><br>
				<i class="fa fa-times"></i>
				<p>Delivered</p>
			</li>
		</ul>
	</div>
{% endblock %}