Online_Courier_Service_Management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Online Courier Service Management Admin'
admin.site.site_title = 'Online Courier Service Management Admin Portal'
admin.site.index_title = 'Welcome to Online Courier Service Management Admin Portal'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('parcels.urls')),
    path('', include('jobs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
                   static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jobs/urls.py
from django.urls import path

import jobs.views as job_views

app_name = 'jobs'

urlpatterns = [
    path('jobs/', job_views.JobListView.as_view(), name='list'),
    path('jobs/<int:pk>/', job_views.JobDetailView.as_view(), name='detail'),
    path('jobs/<int:pk>/apply', job_views.JobApplyView.as_view(), name='apply'),
]

parcels/urls.py
from django.urls import path, reverse

from parcels import views as parcel_views

app_name = 'parcels'

urlpatterns = [
    path('cost-calculator/', parcel_views.CostCalculatorView.as_view(), name='cost_calculator'),
    path('parcels/', parcel_views.ParcelListView.as_view(), name='list'),
    path('parcels/<int:pk>/', parcel_views.ParcelDetailView.as_view(), name='detail'),
    path('parcels/<int:pk>/issue/create', parcel_views.IssueCreateView.as_view(), name='create_issue'),
    path('parcels/create/', parcel_views.ParcelCreateView.as_view(), name='create'),
    path('parcels/track', parcel_views.ParcelTrackView.as_view(), name='track'),
    path('parcels/<int:pk>/update', parcel_views.ParcelUpdateView.as_view(), name='update'),
    path('parcels/<int:pk>/delete', parcel_views.ParcelDeleteView.as_view(), name='delete'),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views as user_views

app_name = 'users'

"""Contains all the urls to access users views."""

urlpatterns = [
    path('', user_views.home, name='home'),
    path('signup/', user_views.CustomerCreationView.as_view(), name='customer_signup'),
    path('user/<int:pk>/', user_views.UserDetailView.as_view(), name='user_detail'),
    path('user/<int:pk>/update', user_views.UserUpdateView.as_view(), name='user_update'),
    path('customer/<int:pk>/', user_views.CustomerDetailView.as_view(), name='customer_detail'),
    path('customer/<int:pk>/update', user_views.CustomerUpdateView.as_view(), name='customer_update'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

templates/base.html
{% load static %}
{% load bootstrap5 %}
{% block bootstrap_css %} {% endblock %}
{% bootstrap_javascript %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon/favicon.ico' %}"/>
        <title>{% block title %} Home {% endblock %}</title>

        {% include 'navigation.html' %}
        {% block override_style %}
            <link rel="stylesheet" href=" {% static 'style.css' %}">
        {% endblock %}
        {% block add_style %}  {% endblock %}

        <!-- font awesome CDN -->
	    <script src="https://use.fontawesome.com/eb66dccf5d.js"></script>
        <!-- font color -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;600;700&display=swap" rel="stylesheet">
    </head>

    <body>
    {% block body %} {% endblock %}
        <main role="main" class="container">
            {% block content %} {% endblock %}
        </main>

        <!-- Call to Action -->
        <section class="cta">
            <h1>Our Currier System provides logistics support in all 64 districts and 490+ sub districts across Bangladesh</h1>
            <a href="" class="hero-btn">CONTACT US</a>
        </section>


        <!-- Footer -->
        <section class="footer">
            <!-- <h4>About Us</h4> -->
            <p>Copyright © 2021 Online Currier Management. All rights reserved. Privacy Policy Terms and Condition</p>
            <div class="icons">
                <i class="fa fa-facebook"></i>
                <i class="fa fa-twitter"></i>
                <i class="fa fa-instagram"></i>
                <i class="fa fa-linkedin"></i>
            </div>
            <p>Made with <i class="fa fa-heart-o"></i> by group 7</p>
        </section>

        <!-- JavaScript for Toggle Menu -->
        <script>

            const navLinks = document.getElementById("navLinks");

            function showMenu(){
                navLinks.style.right = "0";
            }
            function hideMenu(){
                navLinks.style.right = "-200px";
            }

        </script>
    </body>
</html>

templates/cost_calculator.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}
{% block title %} Home {% endblock %}

{% block content %}
	<!------ Cost Calculator ------->
	<div class="booking-form-box">
		<div class="booking-form">
			<label>Product Weight</label>
            <label>
                <input type="text" class="form-control" placeholder="Weight">
            </label>

            <div class="input-grp">
				<label>Product Category</label>
                <label>
                    <select class="custom-select">
                        <option value="1">AC</option>
                        <option value="2">Book</option>
                        <option value="3">AC</option>
                        <option value="4">Book</option>
                        <option value="5">AC</option>
                        <option value="6">Book</option>
                        <option value="7">AC</option>
                        <option value="8">Book</option>
                    </select>
                </label>
            </div>
			<div class="input-grp">
				<label>Delivery Area</label>
                <label>
                    <select class="custom-select">
                        <option value="1">AC</option>
                        <option value="2">Book</option>
                        <option value="3">AC</option>
                        <option value="4">Book</option>
                        <option value="5">AC</option>
                        <option value="6">Book</option>
                        <option value="7">AC</option>
                        <option value="8">Book</option>
                    </select>
                </label>
            </div>

			<div class="radio-btn">
                <label>
                    <input type="radio" class="btn" name="check" checked="checked">
                </label> <span>Product Type</span>
                <label>
                    <input type="radio" class="btn" name="check">
                </label> <span>Fragile</span>
                <label>
                    <input type="radio" class="btn" name="check">
                </label> <span>Liquid</span>

			</div>

			<div class="input-grp">
				<label>Product Quantity</label>
                <label>
                    <input type="number" class="form-control" value="1">
                </label>
            </div>

			<div class="input-grp">
				<button type="button" class = "btn btn-primary flight">Calculate</button>
			</div>

		</div>
	</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}

{% block title %} Home {% endblock %}

{% block body %}
    <section class="header">
        <div class = "text-box">
            <h1>Bangladesh's Biggest Courier System</h1>
            <p>
                Online Courier is Bangladesh’s most trusted on-demand last mile logistics network offering
                tech-enabled one stop delivery solutions.<br> Our vision has been to become the operating
                system for e-commerce in Bangladesh, through a combination of world-class infrastructure,
                logistics operations of the highest quality and cutting-edge technology capabilities.
            </p>
            <a href="" class="hero-btn">Visit Us To know More</a>
        </div>
    </section>
	<!-- Reasons -->
	<section class = "reasons">
		<h1> Why we are the best?</h1>
		<!-- <p>kjdfkl dlfkjkldjf dklfjfkldj lflkjdfklj ldjfdlkj lfkdjfklj</p> -->

		<div class="row">
			<div class="reason-col">
				<h3>Fulfillment solution</h3>
				<p>Through warehousing and fulfillment solution, offers customized service packages with inventory management support, order processing, packaging, after sales support.</p>
			</div>

			<div class="reason-col">
				<h3>Cash on Delivery</h3>
				<p>We provide the option of cash on delivery by collecting the payment in cash at the time of delivery</p>
			</div>

			<div class="reason-col">
				<h3>Reverse Logistics</h3>
				<p>Reverse logistics is provided that allows customers to return their products</p>
			</div>
		</div>
	</section>
	<!-- Services -->
	<section class="services">
		<h1>End-to-end logistics solutions for everyone</h1>
		<!-- <p>kjdfkl dlfkjkldjf dklfjfkldj lflkjdfklj ldjfdlkj lfkdjfklj</p> -->

		<div class="row">
			<div class="service-col">
				<img src="{% static 'images/small-business.jpg' %}" alt="">
				<div class="layer">
					<h3>Small businesses</h3>
				</div>
			</div>

			<div class="service-col">
				<img src="{% static 'images/individuals.jpg' %}" alt="">
				<div class="layer">
					<h3>Individuals</h3>
				</div>
			</div>

			<div class="service-col">
				<img src="{% static 'images/enterprises.jpg' %}" alt="">
				<div class="layer">
					<h3>Enterprises</h3>
				</div>
			</div>
		</div>
	</section>

	<!-- Facilities -->
	<section class="facilities">
		<h1>Our Facilities</h1>
		<!-- <p>kjdfkl dlfkjkldjf dklfjfkldj lflkjdfklj ldjfdlkj lfkdjfklj</p> -->

		<div class="row">
			<div class="facilities-col">
				<img src="{% static 'images/Industry-leading-tech.png' %}" alt="">
				<h3>Industry-leading tech</h3>
				<p>With a brilliant team of engineers driving everything we do, WE offer the best possible service experience powered by superior technology</p>
			</div>

			<div class="facilities-col">
				<img src="{% static 'images/Nationwide-coverage.png' %}" alt="">
				<h3>Nationwide coverage</h3>
				<p>We offer the widest logistics network, covering 64 districts and 490+ sub districts across Bangladesh</p>
			</div>

			<div class="facilities-col">
				<img src="{% static 'images/Fastest-solutions.png' %}" alt="">
				<h3>Fastest solutions</h3>
				<p>Backed by an agile team and dynamic operations, we promise to find the fastest solutions for your needs</p>
			</div>
		</div>
	</section>


	<!-- Reviews -->
	<section class="reviews">
		<h1>What our customer says</h1>
		<!-- <p>kjdfkl dlfkjkldjf dklfjfkldj lflkjdfklj ldjfdlkj lfkdjfklj</p> -->

		<div class="row">
			<div class="review-col">
				<img src="{% static 'images/user1.jpg' %}" alt="">
				<div>
					<p>Faltu Currier, Worst Experience</p>
					<h3>Asif Ahmed</h3>
					<i class="fa fa-star"></i>
					<i class="fa fa-star"></i>
					<i class="fa fa-star"></i>
					<i class="fa fa-star"></i>
					<i class="fa fa-star-o"></i>
				</div>
			</div>

			<div class="review-col">
				<img src="{% static 'images/user2.jpg' %}" alt="">
				<div>
					<p>Best currier service in bangladesh, highly recommended</p>
					<h3>Jaber Al Siam</h3>
					<i class="fa fa-star"></i>
					<i class="fa fa-star"></i>
					<i class="fa fa-star"></i>
					<i class="fa fa-star"></i>
					<i class="fa fa-star-half-o"></i>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/navigation.html
{% load static %}

<nav style="background-color: #1b1b1b">
    <a href="{% url 'users:home' %}"><img src="{% static 'images/logo-courier.png' %}" alt=""></a>
    <div class="nav-links" id="navLinks">
        <i class="fa fa-times" onclick="hideMenu()"></i>
        <ul>
            <li><a href="{% url 'users:home' %}">HOME</a></li>
            <li><a href="{% url 'parcels:list' %}">PARCELS</a></li>
            <li><a href="{% url 'parcels:track' %}">TRACK PARCEL</a></li>
            <li><a href="{% url 'parcels:cost_calculator' %}">COST CALCULATOR</a></li>
            <li><a href="{% url 'jobs:list' %}">CARRIER</a></li>

            {% if user.is_authenticated %}
                {% if user.is_superuser %}
                    <li><a href="/admin/">ADMIN</a></li>
                {% else %}
                    <li><a href="{% url 'users:customer_update' user.id %}">PROFILE</a></li>
                {% endif %}
                <li><a href="{% url 'users:logout' %}">LOGOUT</a></li>

            {% else %}
                <li><a href="{% url 'users:login' %}">LOGIN</a></li>
                <li><a href="{% url 'users:customer_signup' %}">SIGNUP</a></li>
            {% endif %}
        </ul>
    </div>
    <i class="fa fa-bars" onclick="showMenu()"></i>
</nav>