Online_Courier_Service_Management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Online Courier Service Management Admin'
admin.site.site_title = 'Online Courier Service Management Admin Portal'
admin.site.index_title = 'Welcome to Online Courier Service Management Admin Portal'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls')),
    path('', include('parcels.urls')),
    path('', include('jobs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
                   static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jobs/urls.py
from django.urls import path

import jobs.views as job_views

app_name = 'jobs'

urlpatterns = [
    path('jobs/', job_views.JobListView.as_view(), name='list'),
    path('jobs/<int:pk>/', job_views.JobDetailView.as_view(), name='detail'),
    path('jobs/<int:pk>/apply', job_views.JobApplyView.as_view(), name='apply'),
]

jobs/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.

class Job(models.Model):
    TYPE = [
        ('part_time', 'Part Time'),
        ('full_time', 'Full Time'),
        ('contract', 'Contract'),
    ]
    title = models.CharField(max_length=200)
    position = models.CharField(max_length=200)
    type = models.CharField(max_length=200, choices=TYPE, default=None)
    location = models.CharField(max_length=100)
    vacancy = models.PositiveIntegerField()
    description = models.CharField(max_length=200)
    skill_requirements = models.CharField(max_length=1000)
    education_requirements = models.CharField(max_length=1000)
    experience_requirements = models.CharField(max_length=1000)
    salary = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse('jobs:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super(Job, self).save(*args, **kwargs)


class Applicant(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    resume = models.FileField(upload_to='jobs/applicants_resume')
    job = models.ForeignKey(Job, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super(Applicant, self).save(*args, **kwargs)

jobs/forms.py
from django import forms

jobs/views.py
from django import views
from django.contrib import messages
from django.shortcuts import redirect

from jobs.models import Job, Applicant


# Create your views here.


class JobListView(views.generic.ListView):
    def get_queryset(self):
        return Job.objects.all()


class JobDetailView(views.generic.DetailView):
    model = Job


class JobApplyView(views.generic.edit.CreateView):
    model = Applicant
    fields = ['name', 'email', 'resume', ]

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        applicant = form.save(self)
        applicant.job = Job.objects.get(pk=kwargs['pk'])
        applicant.save()
        messages.success(request, 'You have applied successfully, we will contact you for further instruction.')
        return redirect('jobs:list')

templates/jobs/applicant_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}


{% block content %}
    <div class="content-section">
      <form method="post">
          {% bootstrap_messages %}
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="d-grid gap-2">
              <button class="btn btn-outline-info" type="submit">Place</button>
          </div>
      </form>
    </div>
{% endblock %}

templates/jobs/job_detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% block bootstrap_css %} {% bootstrap_css %} {% endblock %}
{% block title %} Apply {% endblock %}

{% block content %}
    <!------ Job Description ------->
    {# context is object #}
    <section class="about-us">
        <div class="row">
            <div class="about-col">
                <h1> {{ object.title }} </h1>
                <p> {{ object.get_type_display }} {{ object.position }} </p>
                <h2> Description </h2>
                <p> {{ object.description }} </p>
                <i class="fa fa-briefcase"></i> <span> Experience: {{ object.experience_requirements }} </span><br>
                ৳ Salary: {{ object.salary }} </span><br>
                <i class="fa fa-map-marker"></i> <span> Location: {{ object.location }} </span><br>
                <i class="fa fa-user-times"></i> <span> Vacancy: {{ object.vacancy }} </span><br><br>

                <h2> Skill Requirements </h2>
                <p>
                    {{ object.skill_requirements }}<br>
                    {# {% for skill in object.skill_requirements %}#}
                    {# <i class="fa fa-circle-o"></i>{{ skill }}<br>#}
                    {# {% endfor %}#}
                </p>
                <h2>Education Requirements</h2>
                <p>
                    <i class="fa fa-user-graduate"></i><b> {{ object.education_requirements }} </b><br>
                </p>
                <a href="{% url 'jobs:apply' object.pk %}" class="hero-btn red-btn">APPLY NOW</a>
            </div>
            <div class="about-col">
                <img src="{% static 'images/about.jpg' %}" alt="">
            </div>
        </div>
    </section>
{% endblock %}

templates/jobs/job_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block title %} Jobs {% endblock %}

{% block content %}
    <!-- ------------ Recent Job ---------------- -->
    {# context is object_list #}
    {% bootstrap_messages %}
    <section id="jobs">
        <div class="container">
            <h4 align="center"> CLICK TO APPLY </h4><br>
            {% for job in object_list %}
                <div class="company-details">
                    <div class="reason-col">
                        <a href="{% url 'jobs:detail' job.id %}">
                            <h4><b>{{ job.title }}</b></h4>
                            <p>{{ job.position }}<br>{{ job.get_type_display }}</p>
                            <i class="fa fa-briefcase"></i> <span>{{ job.experience_requirements }}</span><br>
                            <i class="fa fa-inr"></i> <span>{{ job.salary }}</span><br>
                            <i class="fa fa-map-marker"></i> <span> {{ job.location }} </span><br>
                            <i class="fa fa-map-marker"></i> <span> {{ job.vacancy }} </span><br>
                        </a>
                    </div>
                </div>
            {% empty %}
                <li>No job posted yet!</li>
            {% endfor %}
        </div>
    </section>
{% endblock %}